
export type RewardDifficulty = 'EASY' | 'NORMAL' | 'HARD' | 'EXTREME';

export type RewardCategory =
    | 'GOLD'                // 金幣
    | 'EXP'                 // 經驗
    | 'PERM_NONE'           // 永久能力無羈絆
    | 'PERM_SYNERGY'        // 永久能力有羈絆
    | 'BATTLE_SYNERGY'      // 單次戰鬥能力有羈絆
    | 'BATTLE_NONE'         // 單次戰鬥能力無羈絆
    | 'LIVES';              // 玩家生命

export interface RewardDefinition {
    difficulty: RewardDifficulty;
    category: RewardCategory;
    item: string;
    effect: string;
    imageUrl: string;
    synergyId?: string; // Internal ID if category relates to synergy
}

export const REWARD_DATA: RewardDefinition[] = [
    // --- GOLD ---
    { "difficulty": "EASY", "category": "GOLD", "item": "星星碎片", "effect": "可以在商店高價出售，下次準備階段獲得+1金幣", "imageUrl": "item/星星碎片.png" },
    { "difficulty": "NORMAL", "category": "GOLD", "item": "彗星碎片", "effect": "可以在商店高價出售，下次準備階段獲得+2金幣", "imageUrl": "item/彗星碎片.png" },
    { "difficulty": "HARD", "category": "GOLD", "item": "金珠", "effect": "可以在商店高價出售，下次準備階段獲得+3金幣", "imageUrl": "item/金珠.png" },
    { "difficulty": "EXTREME", "category": "GOLD", "item": "巨大金珠", "effect": "可以在商店高價出售，下次準備階段獲得+5金幣", "imageUrl": "item/巨大金珠.png" },
    { "difficulty": "EASY", "category": "GOLD", "item": "老千骰子", "effect": "只會滾出好點數的骰子，下次準備階段免費刷新1次", "imageUrl": "item/老千骰子.png" },
    { "difficulty": "NORMAL", "category": "GOLD", "item": "老千骰子", "effect": "只會滾出好點數的骰子，下次準備階段免費刷新2次", "imageUrl": "item/老千骰子.png" },
    { "difficulty": "HARD", "category": "GOLD", "item": "老千骰子", "effect": "只會滾出好點數的骰子，下次準備階段免費刷新3次", "imageUrl": "item/老千骰子.png" },
    { "difficulty": "EXTREME", "category": "GOLD", "item": "老千骰子", "effect": "只會滾出好點數的骰子，下次準備階段免費刷新5次", "imageUrl": "item/老千骰子.png" },

    // --- BATTLE_NONE (Random/Positional/All) ---
    { "difficulty": "EASY", "category": "BATTLE_NONE", "item": "ＰＰ單項小補劑", "effect": "能夠回復招式點數，我方隨機角色+3攻擊", "imageUrl": "item/ＰＰ單項小補劑.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_NONE", "item": "ＰＰ單項全補劑", "effect": "能夠回復招式點數，我方隨機角色+5攻擊", "imageUrl": "item/ＰＰ單項全補劑.png" },
    { "difficulty": "HARD", "category": "BATTLE_NONE", "item": "ＰＰ多項小補劑", "effect": "能夠回復招式點數，我方隨機角色+10攻擊", "imageUrl": "item/ＰＰ多項小補劑.png" },
    { "difficulty": "EXTREME", "category": "BATTLE_NONE", "item": "ＰＰ多項全補劑", "effect": "能夠回復招式點數，我方隨機角色+20攻擊", "imageUrl": "item/ＰＰ多項全補劑.png" },

    { "difficulty": "EASY", "category": "BATTLE_NONE", "item": "傷藥", "effect": "能夠回復招式點數，我方隨機角色+3生命", "imageUrl": "item/傷藥.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_NONE", "item": "好傷藥", "effect": "能夠回復招式點數，我方隨機角色+5生命", "imageUrl": "item/好傷藥.png" },
    { "difficulty": "HARD", "category": "BATTLE_NONE", "item": "厲害傷藥", "effect": "能夠回復招式點數，我方隨機角色+10生命", "imageUrl": "item/厲害傷藥.png" },
    { "difficulty": "EXTREME", "category": "BATTLE_NONE", "item": "全滿藥", "effect": "能夠回復招式點數，我方隨機角色+20生命", "imageUrl": "item/全滿藥.png" },

    { "difficulty": "NORMAL", "category": "BATTLE_NONE", "item": "活力碎片", "effect": "能夠讓角色重獲生機，我方隨機角色+2攻擊與生命", "imageUrl": "item/活力碎片.png" },
    { "difficulty": "HARD", "category": "BATTLE_NONE", "item": "活力塊", "effect": "能夠讓角色重獲生機，我方隨機角色+3攻擊與生命", "imageUrl": "item/活力塊.png" },

    { "difficulty": "EASY", "category": "BATTLE_NONE", "item": "先制之爪", "effect": "又輕又尖銳的爪子，我方首位角色+2攻擊", "imageUrl": "item/先制之爪.png" },
    { "difficulty": "EASY", "category": "BATTLE_NONE", "item": "突擊背心", "effect": "富有攻擊性的背心，我方首位角色+2生命", "imageUrl": "item/突擊背心.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_NONE", "item": "先制之爪", "effect": "又輕又尖銳的爪子，我方首位角色+4攻擊", "imageUrl": "item/先制之爪.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_NONE", "item": "突擊背心", "effect": "富有攻擊性的背心，我方首位角色+4生命", "imageUrl": "item/突擊背心.png" },
    { "difficulty": "HARD", "category": "BATTLE_NONE", "item": "先制之爪", "effect": "又輕又尖銳的爪子，我方首位角色+8攻擊", "imageUrl": "item/先制之爪.png" },
    { "difficulty": "HARD", "category": "BATTLE_NONE", "item": "突擊背心", "effect": "富有攻擊性的背心，我方首位角色+8生命", "imageUrl": "item/突擊背心.png" },
    { "difficulty": "EXTREME", "category": "BATTLE_NONE", "item": "先制之爪", "effect": "又輕又尖銳的爪子，我方首位角色+12攻擊", "imageUrl": "item/先制之爪.png" },
    { "difficulty": "EXTREME", "category": "BATTLE_NONE", "item": "突擊背心", "effect": "富有攻擊性的背心，我方首位角色+12生命", "imageUrl": "item/突擊背心.png" },

    { "difficulty": "NORMAL", "category": "BATTLE_NONE", "item": "要害攻擊", "effect": "擊中要害的機率提高，我方全體角色+1攻擊", "imageUrl": "item/要害攻擊.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_NONE", "item": "命中強化", "effect": "提高戰鬥中的命中，我方全體角色+1攻擊", "imageUrl": "item/命中強化.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_NONE", "item": "力量強化", "effect": "提高戰鬥中的攻擊，我方全體角色+1攻擊", "imageUrl": "item/力量強化.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_NONE", "item": "特攻強化", "effect": "提高戰鬥中的特攻，我方全體角色+1攻擊", "imageUrl": "item/特攻強化.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_NONE", "item": "速度強化", "effect": "提高戰鬥中的速度，我方全體角色+1攻擊", "imageUrl": "item/速度強化.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_NONE", "item": "能力防守", "effect": "能力值不被降低，我方全體角色+1生命", "imageUrl": "item/能力防守.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_NONE", "item": "防禦強化", "effect": "提高戰鬥中的防禦，我方全體角色+1生命", "imageUrl": "item/防禦強化.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_NONE", "item": "特防強化", "effect": "提高戰鬥中的特防，我方全體角色+1生命", "imageUrl": "item/特防強化.png" },

    { "difficulty": "HARD", "category": "BATTLE_NONE", "item": "命中強化", "effect": "提高戰鬥中的命中，我方全體角色+2攻擊", "imageUrl": "item/命中強化.png" },
    { "difficulty": "HARD", "category": "BATTLE_NONE", "item": "力量強化", "effect": "提高戰鬥中的攻擊，我方全體角色+2攻擊", "imageUrl": "item/力量強化.png" },
    { "difficulty": "HARD", "category": "BATTLE_NONE", "item": "特攻強化", "effect": "提高戰鬥中的特攻，我方全體角色+2攻擊", "imageUrl": "item/特攻強化.png" },
    { "difficulty": "HARD", "category": "BATTLE_NONE", "item": "速度強化", "effect": "提高戰鬥中的速度，我方全體角色+2攻擊", "imageUrl": "item/速度強化.png" },
    { "difficulty": "HARD", "category": "BATTLE_NONE", "item": "能力防守", "effect": "能力值不被降低，我方全體角色+2生命", "imageUrl": "item/能力防守.png" },
    { "difficulty": "HARD", "category": "BATTLE_NONE", "item": "防禦強化", "effect": "提高戰鬥中的防禦，我方全體角色+2生命", "imageUrl": "item/防禦強化.png" },
    { "difficulty": "HARD", "category": "BATTLE_NONE", "item": "特防強化", "effect": "提高戰鬥中的特防，我方全體角色+2生命", "imageUrl": "item/特防強化.png" },

    // --- BATTLE_SYNERGY ---
    // --- BATTLE_SYNERGY ---
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Normal", "item": "柿仔果", "effect": "我方全體守住角色+3攻擊", "imageUrl": "item/柿仔果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Ghost", "item": "謎芝果", "effect": "我方全體詛咒角色+3攻擊", "imageUrl": "item/謎芝果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Grass", "item": "霹靂果", "effect": "我方全體吸取角色+3攻擊", "imageUrl": "item/霹靂果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Fire", "item": "蘋野果", "effect": "我方全體熱風角色+3攻擊", "imageUrl": "item/蘋野果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Water", "item": "橙橙果", "effect": "我方全體潮旋角色+3攻擊", "imageUrl": "item/橙橙果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Hard", "item": "文柚果", "effect": "我方全體堅硬角色+3攻擊", "imageUrl": "item/文柚果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Cave", "item": "勿花果", "effect": "我方全體挖洞角色+3攻擊", "imageUrl": "item/勿花果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Snow", "item": "莓莓果", "effect": "我方全體降雪角色+3攻擊", "imageUrl": "item/莓莓果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "SwordDance", "item": "櫻子果", "effect": "我方全體劍舞角色+3攻擊", "imageUrl": "item/櫻子果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Psychic", "item": "芒芒果", "effect": "我方全體念力角色+3攻擊", "imageUrl": "item/芒芒果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "BugBite", "item": "木子果", "effect": "我方全體蟲咬角色+3攻擊", "imageUrl": "item/木子果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Thief", "item": "異奇果", "effect": "我方全體小偷角色+3攻擊", "imageUrl": "item/異奇果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Starter", "item": "星桃果", "effect": "我方全體御三家角色+3攻擊", "imageUrl": "item/星桃果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Triplets", "item": "羅子果", "effect": "我方全體三胞胎角色+3攻擊", "imageUrl": "item/羅子果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Angry", "item": "龍火果", "effect": "我方全體憤怒角色+3攻擊", "imageUrl": "item/龍火果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Trick", "item": "福祿果", "effect": "我方全體戲法角色+3攻擊", "imageUrl": "item/福祿果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Normal", "item": "柿仔果", "effect": "我方全體守住角色+3生命", "imageUrl": "item/柿仔果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Ghost", "item": "謎芝果", "effect": "我方全體詛咒角色+3生命", "imageUrl": "item/謎芝果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Grass", "item": "霹靂果", "effect": "我方全體吸取角色+3生命", "imageUrl": "item/霹靂果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Fire", "item": "蘋野果", "effect": "我方全體熱風角色+3生命", "imageUrl": "item/蘋野果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Water", "item": "橙橙果", "effect": "我方全體潮旋角色+3生命", "imageUrl": "item/橙橙果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Hard", "item": "文柚果", "effect": "我方全體堅硬角色+3生命", "imageUrl": "item/文柚果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Cave", "item": "勿花果", "effect": "我方全體挖洞角色+3生命", "imageUrl": "item/勿花果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Snow", "item": "莓莓果", "effect": "我方全體降雪角色+3生命", "imageUrl": "item/莓莓果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "SwordDance", "item": "櫻子果", "effect": "我方全體劍舞角色+3生命", "imageUrl": "item/櫻子果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Psychic", "item": "芒芒果", "effect": "我方全體念力角色+3生命", "imageUrl": "item/芒芒果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "BugBite", "item": "木子果", "effect": "我方全體蟲咬角色+3生命", "imageUrl": "item/木子果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Thief", "item": "異奇果", "effect": "我方全體小偷角色+3生命", "imageUrl": "item/異奇果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Starter", "item": "星桃果", "effect": "我方全體御三家角色+3生命", "imageUrl": "item/星桃果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Triplets", "item": "羅子果", "effect": "我方全體三胞胎角色+3生命", "imageUrl": "item/羅子果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Angry", "item": "龍火果", "effect": "我方全體憤怒角色+3生命", "imageUrl": "item/龍火果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Trick", "item": "福祿果", "effect": "我方全體戲法角色+3生命", "imageUrl": "item/福祿果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Charge", "item": "萄葡果", "effect": "我方全體電光角色+3攻擊", "imageUrl": "item/萄葡果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Charge", "item": "萄葡果", "effect": "我方全體電光角色+3生命", "imageUrl": "item/萄葡果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Outrage", "item": "番荔果", "effect": "我方全體逆鱗角色+3攻擊", "imageUrl": "item/番荔果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Outrage", "item": "番荔果", "effect": "我方全體逆鱗角色+3生命", "imageUrl": "item/番荔果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Roost", "item": "佛柑果", "effect": "我方全體羽棲角色+3攻擊", "imageUrl": "item/佛柑果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Roost", "item": "佛柑果", "effect": "我方全體羽棲角色+3生命", "imageUrl": "item/佛柑果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Charm", "item": "桃桃果", "effect": "我方全體撒嬌角色+3攻擊", "imageUrl": "item/桃桃果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Charm", "item": "桃桃果", "effect": "我方全體撒嬌角色+3生命", "imageUrl": "item/桃桃果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "BatonPass", "item": "比巴果", "effect": "我方全體接棒角色+3攻擊", "imageUrl": "item/比巴果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "BatonPass", "item": "比巴果", "effect": "我方全體接棒角色+3生命", "imageUrl": "item/比巴果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Intimidate", "item": "利木果", "effect": "我方全體威嚇角色+3攻擊", "imageUrl": "item/利木果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Intimidate", "item": "利木果", "effect": "我方全體威嚇角色+3生命", "imageUrl": "item/利木果.png" },

    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Normal", "item": "柿仔果", "effect": "我方全體守住角色+5攻擊", "imageUrl": "item/柿仔果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Ghost", "item": "謎芝果", "effect": "我方全體詛咒角色+5攻擊", "imageUrl": "item/謎芝果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Grass", "item": "霹靂果", "effect": "我方全體吸取角色+5攻擊", "imageUrl": "item/霹靂果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Fire", "item": "蘋野果", "effect": "我方全體熱風角色+5攻擊", "imageUrl": "item/蘋野果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Water", "item": "橙橙果", "effect": "我方全體潮旋角色+5攻擊", "imageUrl": "item/橙橙果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Hard", "item": "文柚果", "effect": "我方全體堅硬角色+5攻擊", "imageUrl": "item/文柚果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Cave", "item": "勿花果", "effect": "我方全體挖洞角色+5攻擊", "imageUrl": "item/勿花果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Snow", "item": "莓莓果", "effect": "我方全體降雪角色+5攻擊", "imageUrl": "item/莓莓果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "SwordDance", "item": "櫻子果", "effect": "我方全體劍舞角色+5攻擊", "imageUrl": "item/櫻子果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Psychic", "item": "芒芒果", "effect": "我方全體念力角色+5攻擊", "imageUrl": "item/芒芒果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "BugBite", "item": "木子果", "effect": "我方全體蟲咬角色+5攻擊", "imageUrl": "item/木子果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Thief", "item": "異奇果", "effect": "我方全體小偷角色+5攻擊", "imageUrl": "item/異奇果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Starter", "item": "星桃果", "effect": "我方全體御三家角色+5攻擊", "imageUrl": "item/星桃果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Triplets", "item": "羅子果", "effect": "我方全體三胞胎角色+5攻擊", "imageUrl": "item/羅子果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Angry", "item": "龍火果", "effect": "我方全體憤怒角色+5攻擊", "imageUrl": "item/龍火果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Trick", "item": "福祿果", "effect": "我方全體戲法角色+5攻擊", "imageUrl": "item/福祿果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Normal", "item": "柿仔果", "effect": "我方全體守住角色+5生命", "imageUrl": "item/柿仔果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Ghost", "item": "謎芝果", "effect": "我方全體詛咒角色+5生命", "imageUrl": "item/謎芝果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Grass", "item": "霹靂果", "effect": "我方全體吸取角色+5生命", "imageUrl": "item/霹靂果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Fire", "item": "蘋野果", "effect": "我方全體熱風角色+5生命", "imageUrl": "item/蘋野果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Water", "item": "橙橙果", "effect": "我方全體潮旋角色+5生命", "imageUrl": "item/橙橙果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Hard", "item": "文柚果", "effect": "我方全體堅硬角色+5生命", "imageUrl": "item/文柚果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Cave", "item": "勿花果", "effect": "我方全體挖洞角色+5生命", "imageUrl": "item/勿花果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Snow", "item": "莓莓果", "effect": "我方全體降雪角色+5生命", "imageUrl": "item/莓莓果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "SwordDance", "item": "櫻子果", "effect": "我方全體劍舞角色+5生命", "imageUrl": "item/櫻子果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Psychic", "item": "芒芒果", "effect": "我方全體念力角色+5生命", "imageUrl": "item/芒芒果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "BugBite", "item": "木子果", "effect": "我方全體蟲咬角色+5生命", "imageUrl": "item/木子果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Thief", "item": "異奇果", "effect": "我方全體小偷角色+5生命", "imageUrl": "item/異奇果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Starter", "item": "星桃果", "effect": "我方全體御三家角色+5生命", "imageUrl": "item/星桃果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Triplets", "item": "羅子果", "effect": "我方全體三胞胎角色+5生命", "imageUrl": "item/羅子果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Angry", "item": "龍火果", "effect": "我方全體憤怒角色+5生命", "imageUrl": "item/龍火果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Trick", "item": "福祿果", "effect": "我方全體戲法角色+5生命", "imageUrl": "item/福祿果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Charge", "item": "萄葡果", "effect": "我方全體電光角色+5攻擊", "imageUrl": "item/萄葡果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Charge", "item": "萄葡果", "effect": "我方全體電光角色+5生命", "imageUrl": "item/萄葡果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Outrage", "item": "番荔果", "effect": "我方全體逆鱗角色+5攻擊", "imageUrl": "item/番荔果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Outrage", "item": "番荔果", "effect": "我方全體逆鱗角色+5生命", "imageUrl": "item/番荔果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Roost", "item": "佛柑果", "effect": "我方全體羽棲角色+5攻擊", "imageUrl": "item/佛柑果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Roost", "item": "佛柑果", "effect": "我方全體羽棲角色+5生命", "imageUrl": "item/佛柑果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Charm", "item": "桃桃果", "effect": "我方全體撒嬌角色+5攻擊", "imageUrl": "item/桃桃果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Charm", "item": "桃桃果", "effect": "我方全體撒嬌角色+5生命", "imageUrl": "item/桃桃果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "BatonPass", "item": "比巴果", "effect": "我方全體接棒角色+5攻擊", "imageUrl": "item/比巴果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "BatonPass", "item": "比巴果", "effect": "我方全體接棒角色+5生命", "imageUrl": "item/比巴果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Intimidate", "item": "利木果", "effect": "我方全體威嚇角色+5攻擊", "imageUrl": "item/利木果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Intimidate", "item": "利木果", "effect": "我方全體威嚇角色+5生命", "imageUrl": "item/利木果.png" },

    { "difficulty": "HARD", "category": "BATTLE_SYNERGY", "synergyId": "Normal", "item": "淨空石板", "effect": "淨空的石板，雙方守住角色+5攻擊與+5生命", "imageUrl": "item/淨空石板.webp" },
    { "difficulty": "HARD", "category": "BATTLE_SYNERGY", "synergyId": "Ghost", "item": "妖怪石板", "effect": "妖怪的石板，雙方詛咒角色+5攻擊與+5生命", "imageUrl": "item/妖怪石板.png" },
    { "difficulty": "HARD", "category": "BATTLE_SYNERGY", "synergyId": "Grass", "item": "碧綠石板", "effect": "碧綠的石板，雙方吸取角色+5攻擊與+5生命", "imageUrl": "item/碧綠石板.png" },
    { "difficulty": "HARD", "category": "BATTLE_SYNERGY", "synergyId": "Fire", "item": "火球石板", "effect": "火球的石板，雙方熱風角色+5攻擊與+5生命", "imageUrl": "item/火球石板.png" },
    { "difficulty": "HARD", "category": "BATTLE_SYNERGY", "synergyId": "Water", "item": "水滴石板", "effect": "水滴的石板，雙方潮旋角色+5攻擊與+5生命", "imageUrl": "item/水滴石板.png" },
    { "difficulty": "HARD", "category": "BATTLE_SYNERGY", "synergyId": "Hard", "item": "鋼鐵石板", "effect": "鋼鐵的石板，雙方堅硬角色+5攻擊與+5生命", "imageUrl": "item/鋼鐵石板.png" },
    { "difficulty": "HARD", "category": "BATTLE_SYNERGY", "synergyId": "Cave", "item": "大地石板", "effect": "大地的石板，雙方挖洞角色+5攻擊與+5生命", "imageUrl": "item/大地石板.png" },
    { "difficulty": "HARD", "category": "BATTLE_SYNERGY", "synergyId": "Snow", "item": "冰柱石板", "effect": "冰柱的石板，雙方降雪角色+5攻擊與+5生命", "imageUrl": "item/冰柱石板.png" },
    { "difficulty": "HARD", "category": "BATTLE_SYNERGY", "synergyId": "SwordDance", "item": "拳頭石板", "effect": "拳頭的石板，雙方劍舞角色+5攻擊與+5生命", "imageUrl": "item/拳頭石板.png" },
    { "difficulty": "HARD", "category": "BATTLE_SYNERGY", "synergyId": "Psychic", "item": "神奇石板", "effect": "神奇的石板，雙方念力角色+5攻擊與+5生命", "imageUrl": "item/神奇石板.png" },
    { "difficulty": "HARD", "category": "BATTLE_SYNERGY", "synergyId": "BugBite", "item": "玉蟲石板", "effect": "玉蟲的石板，雙方蟲咬角色+5攻擊與+5生命", "imageUrl": "item/玉蟲石板.png" },
    { "difficulty": "HARD", "category": "BATTLE_SYNERGY", "synergyId": "Thief", "item": "惡顏石板", "effect": "惡顏的石板，雙方小偷角色+5攻擊與+5生命", "imageUrl": "item/惡顏石板.png" },
    { "difficulty": "HARD", "category": "BATTLE_SYNERGY", "synergyId": "Charge", "item": "雷電石板", "effect": "雷電的石板，雙方電光角色+5攻擊與+5生命", "imageUrl": "item/雷電石板.png" },
    { "difficulty": "HARD", "category": "BATTLE_SYNERGY", "synergyId": "Outrage", "item": "龍之石板", "effect": "龍之石板，雙方逆鱗角色+5攻擊與+5生命", "imageUrl": "item/龍之石板.png" },
    { "difficulty": "HARD", "category": "BATTLE_SYNERGY", "synergyId": "Roost", "item": "藍天石板", "effect": "藍天的石板，雙方羽棲角色+5攻擊與+5生命", "imageUrl": "item/藍天石板.png" },
    { "difficulty": "HARD", "category": "BATTLE_SYNERGY", "synergyId": "Charm", "item": "妖精石板", "effect": "妖精的石板，雙方撒嬌角色+5攻擊與+5生命", "imageUrl": "item/妖精石板.png" },

    { "difficulty": "EXTREME", "category": "BATTLE_SYNERGY", "synergyId": "Normal", "item": "淨空石板", "effect": "淨空的石板，雙方守住角色+10攻擊與+10生命", "imageUrl": "item/淨空石板.webp" },
    { "difficulty": "EXTREME", "category": "BATTLE_SYNERGY", "synergyId": "Ghost", "item": "妖怪石板", "effect": "妖怪的石板，雙方詛咒角色+10攻擊與+10生命", "imageUrl": "item/妖怪石板.png" },
    { "difficulty": "EXTREME", "category": "BATTLE_SYNERGY", "synergyId": "Grass", "item": "碧綠石板", "effect": "碧綠的石板，雙方吸取角色+10攻擊與+10生命", "imageUrl": "item/碧綠石板.png" },
    { "difficulty": "EXTREME", "category": "BATTLE_SYNERGY", "synergyId": "Fire", "item": "火球石板", "effect": "火球的石板，雙方熱風角色+10攻擊與+10生命", "imageUrl": "item/火球石板.png" },
    { "difficulty": "EXTREME", "category": "BATTLE_SYNERGY", "synergyId": "Water", "item": "水滴石板", "effect": "水滴的石板，雙方潮旋角色+10攻擊與+10生命", "imageUrl": "item/水滴石板.png" },
    { "difficulty": "EXTREME", "category": "BATTLE_SYNERGY", "synergyId": "Hard", "item": "鋼鐵石板", "effect": "鋼鐵的石板，雙方堅硬角色+10攻擊與+10生命", "imageUrl": "item/鋼鐵石板.png" },
    { "difficulty": "EXTREME", "category": "BATTLE_SYNERGY", "synergyId": "Cave", "item": "大地石板", "effect": "大地的石板，雙方挖洞角色+10攻擊與+10生命", "imageUrl": "item/大地石板.png" },
    { "difficulty": "EXTREME", "category": "BATTLE_SYNERGY", "synergyId": "Snow", "item": "冰柱石板", "effect": "冰柱的石板，雙方降雪角色+10攻擊與+10生命", "imageUrl": "item/冰柱石板.png" },
    { "difficulty": "EXTREME", "category": "BATTLE_SYNERGY", "synergyId": "SwordDance", "item": "拳頭石板", "effect": "拳頭的石板，雙方劍舞角色+10攻擊與+10生命", "imageUrl": "item/拳頭石板.png" },
    { "difficulty": "EXTREME", "category": "BATTLE_SYNERGY", "synergyId": "Psychic", "item": "神奇石板", "effect": "神奇的石板，雙方念力角色+10攻擊與+10生命", "imageUrl": "item/神奇石板.png" },
    { "difficulty": "EXTREME", "category": "BATTLE_SYNERGY", "synergyId": "BugBite", "item": "玉蟲石板", "effect": "玉蟲的石板，雙方蟲咬角色+10攻擊與+10生命", "imageUrl": "item/玉蟲石板.png" },
    { "difficulty": "EXTREME", "category": "BATTLE_SYNERGY", "synergyId": "Thief", "item": "惡顏石板", "effect": "惡顏的石板，雙方小偷角色+10攻擊與+10生命", "imageUrl": "item/惡顏石板.png" },
    { "difficulty": "EXTREME", "category": "BATTLE_SYNERGY", "synergyId": "Charge", "item": "雷電石板", "effect": "雷電的石板，雙方電光角色+10攻擊與+10生命", "imageUrl": "item/雷電石板.png" },
    { "difficulty": "EXTREME", "category": "BATTLE_SYNERGY", "synergyId": "Outrage", "item": "龍之石板", "effect": "龍之石板，雙方逆鱗角色+10攻擊與+10生命", "imageUrl": "item/龍之石板.png" },
    { "difficulty": "EXTREME", "category": "BATTLE_SYNERGY", "synergyId": "Roost", "item": "藍天石板", "effect": "藍天的石板，雙方羽棲角色+10攻擊與+10生命", "imageUrl": "item/藍天石板.png" },
    { "difficulty": "EXTREME", "category": "BATTLE_SYNERGY", "synergyId": "Charm", "item": "妖精石板", "effect": "妖精的石板，雙方撒嬌角色+10攻擊與+10生命", "imageUrl": "item/妖精石板.png" },

    // --- PERM_NONE ---
    { "difficulty": "HARD", "category": "PERM_NONE", "item": "腐朽的劍", "effect": "過去擊退災厄的劍，隊伍中的首位角色+3攻擊", "imageUrl": "item/腐朽的劍.png" },
    { "difficulty": "HARD", "category": "PERM_NONE", "item": "腐朽的盾", "effect": "過去擊退災厄的盾，隊伍中的首位角色+3生命", "imageUrl": "item/腐朽的盾.png" },
    { "difficulty": "EXTREME", "category": "PERM_NONE", "item": "腐朽的劍", "effect": "過去擊退災厄的劍，隊伍中的首位角色+5攻擊", "imageUrl": "item/腐朽的劍.png" },
    { "difficulty": "EXTREME", "category": "PERM_NONE", "item": "腐朽的盾", "effect": "過擊退災厄的盾，隊伍中的首位角色+5生命", "imageUrl": "item/腐朽的盾.png" },

    { "difficulty": "HARD", "category": "PERM_NONE", "item": "力量鏡", "effect": "充滿力量的鏡子，隊伍中的全體角色+2攻擊-1生命", "imageUrl": "item/力量鏡.png" },
    { "difficulty": "HARD", "category": "PERM_NONE", "item": "力量護踝", "effect": "充滿力量的護踝，隊伍中的全體角色+2攻擊-1生命", "imageUrl": "item/力量護踝.png" },
    { "difficulty": "HARD", "category": "PERM_NONE", "item": "力量護腕", "effect": "充滿力量的護腕，隊伍中的全體角色+2攻擊-1生命", "imageUrl": "item/力量護腕.png" },
    { "difficulty": "HARD", "category": "PERM_NONE", "item": "力量負重", "effect": "充滿負荷的護具，隊伍中的全體角色+2生命-1攻擊", "imageUrl": "item/力量負重.png" },
    { "difficulty": "HARD", "category": "PERM_NONE", "item": "力量腰帶", "effect": "充滿負荷的腰帶，隊伍中的全體角色+2生命-1攻擊", "imageUrl": "item/力量腰帶.png" },
    { "difficulty": "HARD", "category": "PERM_NONE", "item": "力量束帶", "effect": "充滿負荷的束帶，隊伍中的全體角色+2生命-1攻擊", "imageUrl": "item/力量束帶.png" },
    { "difficulty": "EXTREME", "category": "PERM_NONE", "item": "力量鏡", "effect": "充滿力量的鏡子，隊伍中的全體角色+4攻擊-2生命", "imageUrl": "item/力量鏡.png" },
    { "difficulty": "EXTREME", "category": "PERM_NONE", "item": "力量護踝", "effect": "充滿力量的護踝，隊伍中的全體角色+4攻擊-2生命", "imageUrl": "item/力量護踝.png" },
    { "difficulty": "EXTREME", "category": "PERM_NONE", "item": "力量護腕", "effect": "充滿力量的護腕，隊伍中的全體角色+4攻擊-2生命", "imageUrl": "item/力量護腕.png" },
    { "difficulty": "EXTREME", "category": "PERM_NONE", "item": "力量負重", "effect": "充滿負荷的護具，隊伍中的全體角色+4生命-2攻擊", "imageUrl": "item/力量負重.png" },
    { "difficulty": "EXTREME", "category": "PERM_NONE", "item": "力量腰帶", "effect": "充滿負荷的腰帶，隊伍中的全體角色+4生命-2攻擊", "imageUrl": "item/力量腰帶.png" },
    { "difficulty": "EXTREME", "category": "PERM_NONE", "item": "力量束帶", "effect": "充滿負荷的束帶，隊伍中的全體角色+4生命-2攻擊", "imageUrl": "item/力量束帶.png" },

    // --- MINTS (EASY) ---
    { "difficulty": "EASY", "category": "PERM_NONE", "item": "怕寂寞薄荷", "effect": "攻擊變得容易提高，我方隨機角色+3攻擊-1生命", "imageUrl": "item/紅色薄荷.png" },
    { "difficulty": "EASY", "category": "PERM_NONE", "item": "固執薄荷", "effect": "攻擊變得容易提高，我方隨機角色+3攻擊-1生命", "imageUrl": "item/紅色薄荷.png" },
    { "difficulty": "EASY", "category": "PERM_NONE", "item": "頑皮薄荷", "effect": "攻擊變得容易提高，我方隨機角色+3攻擊-1生命", "imageUrl": "item/紅色薄荷.png" },
    { "difficulty": "EASY", "category": "PERM_NONE", "item": "勇敢薄荷", "effect": "攻擊變得容易提高，我方隨機角色+3攻擊-1生命", "imageUrl": "item/紅色薄荷.png" },
    { "difficulty": "EASY", "category": "PERM_NONE", "item": "大膽薄荷", "effect": "特攻變得容易提高，我方隨機角色+3攻擊-1生命", "imageUrl": "item/藍色薄荷.png" },
    { "difficulty": "EASY", "category": "PERM_NONE", "item": "淘氣薄荷", "effect": "特攻變得容易提高，我方隨機角色+3攻擊-1生命", "imageUrl": "item/藍色薄荷.png" },
    { "difficulty": "EASY", "category": "PERM_NONE", "item": "樂天薄荷", "effect": "特攻變得容易提高，我方隨機角色+3攻擊-1生命", "imageUrl": "item/藍色薄荷.png" },
    { "difficulty": "EASY", "category": "PERM_NONE", "item": "悠閒薄荷", "effect": "特攻變得容易提高，我方隨機角色+3攻擊-1生命", "imageUrl": "item/藍色薄荷.png" },
    { "difficulty": "EASY", "category": "PERM_NONE", "item": "內斂薄荷", "effect": "防禦變得容易提高，我方隨機角色+3生命-1攻擊", "imageUrl": "item/淺藍薄荷.png" },
    { "difficulty": "EASY", "category": "PERM_NONE", "item": "慢吞吞薄荷", "effect": "防禦變得容易提高，我方隨機角色+3生命-1攻擊", "imageUrl": "item/淺藍薄荷.png" },
    { "difficulty": "EASY", "category": "PERM_NONE", "item": "馬虎薄荷", "effect": "防禦變得容易提高，我方隨機角色+3生命-1攻擊", "imageUrl": "item/淺藍薄荷.png" },
    { "difficulty": "EASY", "category": "PERM_NONE", "item": "冷靜薄荷", "effect": "防禦變得容易提高，我方隨機角色+3生命-1攻擊", "imageUrl": "item/淺藍薄荷.png" },
    { "difficulty": "EASY", "category": "PERM_NONE", "item": "溫和薄荷", "effect": "特防變得容易提高，我方隨機角色+3生命-1攻擊", "imageUrl": "item/粉色薄荷.png" },
    { "difficulty": "EASY", "category": "PERM_NONE", "item": "溫順薄荷", "effect": "特防變得容易提高，我方隨機角色+3生命-1攻擊", "imageUrl": "item/粉色薄荷.png" },
    { "difficulty": "EASY", "category": "PERM_NONE", "item": "慎重薄荷", "effect": "特防變得容易提高，我方隨機角色+3生命-1攻擊", "imageUrl": "item/粉色薄荷.png" },
    { "difficulty": "EASY", "category": "PERM_NONE", "item": "爽朗薄荷", "effect": "特防變得容易提高，我方隨機角色+3生命-1攻擊", "imageUrl": "item/粉色薄荷.png" },
    { "difficulty": "EASY", "category": "PERM_NONE", "item": "自大薄荷", "effect": "特防變得容易提高，我方隨機角色+3生命-1攻擊", "imageUrl": "item/粉色薄荷.png" },
    { "difficulty": "EASY", "category": "PERM_NONE", "item": "膽小薄荷", "effect": "速度變得容易提高，我方隨機角色+3攻擊-1生命", "imageUrl": "item/綠色薄荷.png" },
    { "difficulty": "EASY", "category": "PERM_NONE", "item": "急躁薄荷", "effect": "速度變得容易提高，我方隨機角色+3攻擊-1生命", "imageUrl": "item/綠色薄荷.png" },
    { "difficulty": "EASY", "category": "PERM_NONE", "item": "爽朗薄荷", "effect": "速度變得容易提高，我方隨機角色+3攻擊-1生命", "imageUrl": "item/綠色薄荷.png" },
    { "difficulty": "EASY", "category": "PERM_NONE", "item": "天真薄荷", "effect": "速度變得容易提高，我方隨機角色+3攻擊-1生命", "imageUrl": "item/綠色薄荷.png" },
    { "difficulty": "NORMAL", "category": "PERM_NONE", "item": "認真薄荷", "effect": "會讓能力均衡地成長，我方隨機角色+1攻擊+1生命", "imageUrl": "item/白色薄荷.png" },

    // --- MINTS (NORMAL) ---
    { "difficulty": "NORMAL", "category": "PERM_NONE", "item": "怕寂寞薄荷", "effect": "攻擊變得容易提高，我方隨機角色+5攻擊-1生命", "imageUrl": "item/紅色薄荷.png" },
    { "difficulty": "NORMAL", "category": "PERM_NONE", "item": "固執薄荷", "effect": "攻擊變得容易提高，我方隨機角色+5攻擊-1生命", "imageUrl": "item/紅色薄荷.png" },
    { "difficulty": "NORMAL", "category": "PERM_NONE", "item": "頑皮薄荷", "effect": "攻擊變得容易提高，我方隨機角色+5攻擊-1生命", "imageUrl": "item/紅色薄荷.png" },
    { "difficulty": "NORMAL", "category": "PERM_NONE", "item": "勇敢薄荷", "effect": "攻擊變得容易提高，我方隨機角色+5攻擊-1生命", "imageUrl": "item/紅色薄荷.png" },
    { "difficulty": "NORMAL", "category": "PERM_NONE", "item": "大膽薄荷", "effect": "特攻變得容易提高，我方隨機角色+5攻擊-1生命", "imageUrl": "item/藍色薄荷.png" },
    { "difficulty": "NORMAL", "category": "PERM_NONE", "item": "淘氣薄荷", "effect": "特攻變得容易提高，我方隨機角色+5攻擊-1生命", "imageUrl": "item/藍色薄荷.png" },
    { "difficulty": "NORMAL", "category": "PERM_NONE", "item": "樂天薄荷", "effect": "特攻變得容易提高，我方隨機角色+5攻擊-1生命", "imageUrl": "item/藍色薄荷.png" },
    { "difficulty": "NORMAL", "category": "PERM_NONE", "item": "悠閒薄荷", "effect": "特攻變得容易提高，我方隨機角色+5攻擊-1生命", "imageUrl": "item/藍色薄荷.png" },
    { "difficulty": "NORMAL", "category": "PERM_NONE", "item": "內斂薄荷", "effect": "防禦變得容易提高，我方隨機角色+5生命-1攻擊", "imageUrl": "item/淺藍薄荷.png" },
    { "difficulty": "NORMAL", "category": "PERM_NONE", "item": "慢吞吞薄荷", "effect": "防禦變得容易提高，我方隨機角色+5生命-1攻擊", "imageUrl": "item/淺藍薄荷.png" },
    { "difficulty": "NORMAL", "category": "PERM_NONE", "item": "馬虎薄荷", "effect": "防禦變得容易提高，我方隨機角色+5生命-1攻擊", "imageUrl": "item/淺藍薄荷.png" },
    { "difficulty": "NORMAL", "category": "PERM_NONE", "item": "冷靜薄荷", "effect": "防禦變得容易提高，我方隨機角色+5生命-1攻擊", "imageUrl": "item/淺藍薄荷.png" },
    { "difficulty": "NORMAL", "category": "PERM_NONE", "item": "溫和薄荷", "effect": "特防變得容易提高，我方隨機角色+5生命-1攻擊", "imageUrl": "item/粉色薄荷.png" },
    { "difficulty": "NORMAL", "category": "PERM_NONE", "item": "溫順薄荷", "effect": "特防變得容易提高，我方隨機角色+5生命-1攻擊", "imageUrl": "item/粉色薄荷.png" },
    { "difficulty": "NORMAL", "category": "PERM_NONE", "item": "慎重薄荷", "effect": "特防變得容易提高，我方隨機角色+5生命-1攻擊", "imageUrl": "item/粉色薄荷.png" },
    { "difficulty": "NORMAL", "category": "PERM_NONE", "item": "爽朗薄荷", "effect": "特防變得容易提高，我方隨機角色+5生命-1攻擊", "imageUrl": "item/粉色薄荷.png" },
    { "difficulty": "NORMAL", "category": "PERM_NONE", "item": "自大薄荷", "effect": "特防變得容易提高，我方隨機角色+5生命-1攻擊", "imageUrl": "item/粉色薄荷.png" },
    { "difficulty": "NORMAL", "category": "PERM_NONE", "item": "膽小薄荷", "effect": "速度變得容易提高，我方隨機角色+5攻擊-1生命", "imageUrl": "item/綠色薄荷.png" },
    { "difficulty": "NORMAL", "category": "PERM_NONE", "item": "急躁薄荷", "effect": "速度變得容易提高，我方隨機角色+5攻擊-1生命", "imageUrl": "item/綠色薄荷.png" },
    { "difficulty": "NORMAL", "category": "PERM_NONE", "item": "爽朗薄荷", "effect": "速度變得容易提高，我方隨機角色+5攻擊-1生命", "imageUrl": "item/綠色薄荷.png" },
    { "difficulty": "NORMAL", "category": "PERM_NONE", "item": "天真薄荷", "effect": "速度變得容易提高，我方隨機角色+5攻擊-1生命", "imageUrl": "item/綠色薄荷.png" },
    { "difficulty": "NORMAL", "category": "PERM_NONE", "item": "認真薄荷", "effect": "會讓能力均衡地成長，我方隨機角色+2攻擊+2生命", "imageUrl": "item/白色薄荷.png" },

    // --- PERM_SYNERGY ---
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Normal", "item": "絲綢圍巾", "effect": "強化隊伍中的守住角色，+2攻擊或生命", "imageUrl": "item/絲綢圍巾.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Ghost", "item": "詛咒之符", "effect": "強化隊伍中的詛咒角色，+2攻擊或生命", "imageUrl": "item/詛咒之符.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Grass", "item": "奇跡種子", "effect": "強化隊伍中的吸取角色，+2攻擊或生命", "imageUrl": "item/奇跡種子.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Fire", "item": "木炭", "effect": "強化隊伍中的熱風角色，+2攻擊或生命", "imageUrl": "item/木炭.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Water", "item": "神秘水滴", "effect": "強化隊伍中的潮旋角色，+2攻擊或生命", "imageUrl": "item/神秘水滴.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Hard", "item": "硬石頭", "effect": "強化隊伍中的堅硬角色，+2攻擊或生命", "imageUrl": "item/硬石頭.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Cave", "item": "柔軟沙子", "effect": "強化隊伍中的挖洞角色，+2攻擊或生命", "imageUrl": "item/柔軟沙子.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Snow", "item": "不融冰", "effect": "強化隊伍中的降雪角色，+2攻擊或生命", "imageUrl": "item/不融冰.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "SwordDance", "item": "黑帶", "effect": "強化隊伍中的劍舞角色，+2攻擊或生命", "imageUrl": "item/黑帶.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Psychic", "item": "彎曲的湯匙", "effect": "強化隊伍中的念力角色，+2攻擊或生命", "imageUrl": "item/彎曲的湯匙.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "BugBite", "item": "銀粉", "effect": "強化隊伍中的蟲咬角色，+2攻擊或生命", "imageUrl": "item/銀粉.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Thief", "item": "黑色眼鏡", "effect": "強化隊伍中的小偷角色，+2攻擊或生命", "imageUrl": "item/黑色眼鏡.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Starter", "item": "幸運草糖飾", "effect": "強化隊伍中的御三家角色，+2攻擊或生命", "imageUrl": "item/幸運草糖飾.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Triplets", "item": "野莓糖飾", "effect": "強化隊伍中的三胞胎角色，+2攻擊或生命", "imageUrl": "item/野莓糖飾.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Angry", "item": "拳擊手套", "effect": "強化隊伍中的憤怒角色，+2攻擊或生命", "imageUrl": "item/拳擊手套.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Trick", "item": "客房服務", "effect": "強化隊伍中的戲法角色，+2攻擊或生命", "imageUrl": "item/客房服務.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Charge", "item": "磁鐵", "effect": "強化隊伍中的電光角色，+2攻擊或生命", "imageUrl": "item/磁鐵.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Outrage", "item": "龍之牙", "effect": "強化隊伍中的逆鱗角色，+2攻擊或生命", "imageUrl": "item/龍之牙.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Roost", "item": "銳利鳥嘴", "effect": "強化隊伍中的羽棲角色，+2攻擊或生命", "imageUrl": "item/銳利鳥嘴.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Charm", "item": "妖精之羽", "effect": "強化隊伍中的撒嬌角色，+2攻擊或生命", "imageUrl": "item/妖精之羽.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "BatonPass", "item": "紅牌", "effect": "強化隊伍中的接棒角色，+2攻擊或生命", "imageUrl": "item/紅牌.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Intimidate", "item": "王者之證", "effect": "強化隊伍中的威嚇角色，+2攻擊或生命", "imageUrl": "item/王者之證.png" },

    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Normal", "item": "絲綢圍巾", "effect": "強化隊伍中的守住角色，+3攻擊或生命", "imageUrl": "item/絲綢圍巾.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Ghost", "item": "詛咒之符", "effect": "強化隊伍中的詛咒角色，+3攻擊或生命", "imageUrl": "item/詛咒之符.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Grass", "item": "奇跡種子", "effect": "強化隊伍中的吸取角色，+3攻擊或生命", "imageUrl": "item/奇跡種子.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Fire", "item": "木炭", "effect": "強化隊伍中的熱風角色，+3攻擊或生命", "imageUrl": "item/木炭.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Water", "item": "神秘水滴", "effect": "強化隊伍中的潮旋角色，+3攻擊或生命", "imageUrl": "item/神秘水滴.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Hard", "item": "硬石頭", "effect": "強化隊伍中的堅硬角色，+3攻擊或生命", "imageUrl": "item/硬石頭.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Cave", "item": "柔軟沙子", "effect": "強化隊伍中的挖洞角色，+3攻擊或生命", "imageUrl": "item/柔軟沙子.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Snow", "item": "不融冰", "effect": "強化隊伍中的降雪角色，+3攻擊或生命", "imageUrl": "item/不融冰.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "SwordDance", "item": "黑帶", "effect": "強化隊伍中的劍舞角色，+3攻擊或生命", "imageUrl": "item/黑帶.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Psychic", "item": "彎曲的湯匙", "effect": "強化隊伍中的念力角色，+3攻擊或生命", "imageUrl": "item/彎曲的湯匙.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "BugBite", "item": "銀粉", "effect": "強化隊伍中的蟲咬角色，+3攻擊或生命", "imageUrl": "item/銀粉.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Thief", "item": "黑色眼鏡", "effect": "強化隊伍中的小偷角色，+3攻擊或生命", "imageUrl": "item/黑色眼鏡.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Starter", "item": "幸運草糖飾", "effect": "強化隊伍中的御三家角色，+3攻擊或生命", "imageUrl": "item/幸運草糖飾.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Triplets", "item": "野莓糖飾", "effect": "強化隊伍中的三胞胎角色，+3攻擊或生命", "imageUrl": "item/野莓糖飾.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Angry", "item": "拳擊手套", "effect": "強化隊伍中的憤怒角色，+3攻擊或生命", "imageUrl": "item/拳擊手套.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Trick", "item": "客房服務", "effect": "強化隊伍中的戲法角色，+3攻擊或生命", "imageUrl": "item/客房服務.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Charge", "item": "磁鐵", "effect": "強化隊伍中的電光角色，+3攻擊或生命", "imageUrl": "item/磁鐵.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Outrage", "item": "龍之牙", "effect": "強化隊伍中的逆鱗角色，+3攻擊或生命", "imageUrl": "item/龍之牙.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Roost", "item": "銳利鳥嘴", "effect": "強化隊伍中的羽棲角色，+3攻擊或生命", "imageUrl": "item/銳利鳥嘴.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Charm", "item": "妖精之羽", "effect": "強化隊伍中的撒嬌角色，+3攻擊或生命", "imageUrl": "item/妖精之羽.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "BatonPass", "item": "紅牌", "effect": "強化隊伍中的接棒角色，+3攻擊或生命", "imageUrl": "item/紅牌.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Intimidate", "item": "王者之證", "effect": "強化隊伍中的威嚇角色，+3攻擊或生命", "imageUrl": "item/王者之證.png" },

    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Normal", "item": "絲綢圍巾", "effect": "強化隊伍中的守住角色，+4攻擊或生命", "imageUrl": "item/絲綢圍巾.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Ghost", "item": "詛咒之符", "effect": "強化隊伍中的詛咒角色，+4攻擊或生命", "imageUrl": "item/詛咒之符.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Grass", "item": "奇跡種子", "effect": "強化隊伍中的吸取角色，+4攻擊或生命", "imageUrl": "item/奇跡種子.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Fire", "item": "木炭", "effect": "強化隊伍中的熱風角色，+4攻擊或生命", "imageUrl": "item/木炭.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Water", "item": "神秘水滴", "effect": "強化隊伍中的潮旋角色，+4攻擊或生命", "imageUrl": "item/神秘水滴.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Hard", "item": "硬石頭", "effect": "強化隊伍中的堅硬角色，+4攻擊或生命", "imageUrl": "item/硬石頭.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Cave", "item": "柔軟沙子", "effect": "強化隊伍中的挖洞角色，+4攻擊或生命", "imageUrl": "item/柔軟沙子.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Snow", "item": "不融冰", "effect": "強化隊伍中的降雪角色，+4攻擊或生命", "imageUrl": "item/不融冰.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "SwordDance", "item": "黑帶", "effect": "強化隊伍中的劍舞角色，+4攻擊或生命", "imageUrl": "item/黑帶.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Psychic", "item": "彎曲的湯匙", "effect": "強化隊伍中的念力角色，+4攻擊或生命", "imageUrl": "item/彎曲的湯匙.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "BugBite", "item": "銀粉", "effect": "強化隊伍中的蟲咬角色，+4攻擊或生命", "imageUrl": "item/銀粉.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Thief", "item": "黑色眼鏡", "effect": "強化隊伍中的小偷角色，+4攻擊或生命", "imageUrl": "item/黑色眼鏡.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Starter", "item": "幸運草糖飾", "effect": "強化隊伍中的御三家角色，+4攻擊或生命", "imageUrl": "item/幸運草糖飾.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Triplets", "item": "野莓糖飾", "effect": "強化隊伍中的三胞胎角色，+4攻擊或生命", "imageUrl": "item/野莓糖飾.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Angry", "item": "拳擊手套", "effect": "強化隊伍中的憤怒角色，+4攻擊或生命", "imageUrl": "item/拳擊手套.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Trick", "item": "客房服務", "effect": "強化隊伍中的戲法角色，+4攻擊或生命", "imageUrl": "item/客房服務.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Charge", "item": "磁鐵", "effect": "強化隊伍中的電光角色，+4攻擊或生命", "imageUrl": "item/磁鐵.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Outrage", "item": "龍之牙", "effect": "強化隊伍中的逆鱗角色，+4攻擊或生命", "imageUrl": "item/龍之牙.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Roost", "item": "銳利鳥嘴", "effect": "強化隊伍中的羽棲角色，+4攻擊或生命", "imageUrl": "item/銳利鳥嘴.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Charm", "item": "妖精之羽", "effect": "強化隊伍中的撒嬌角色，+4攻擊或生命", "imageUrl": "item/妖精之羽.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "BatonPass", "item": "紅牌", "effect": "強化隊伍中的接棒角色，+4攻擊或生命", "imageUrl": "item/紅牌.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Intimidate", "item": "王者之證", "effect": "強化隊伍中的威嚇角色，+4攻擊或生命", "imageUrl": "item/王者之證.png" },

    // --- EXP CANDY ---
    { "difficulty": "EASY", "category": "EXP", "item": "經驗糖果ＸＳ", "effect": "讓角色成長的神奇糖果，隨機1名角色EXP+1", "imageUrl": "item/經驗糖果ＸＳ.png" },
    { "difficulty": "NORMAL", "category": "EXP", "item": "經驗糖果Ｓ", "effect": "讓角色成長的神奇糖果，隨機2名角色EXP+1", "imageUrl": "item/經驗糖果Ｓ.png" },
    { "difficulty": "HARD", "category": "EXP", "item": "經驗糖果Ｍ", "effect": "讓角色成長的神奇糖果，隨機3名角色EXP+1", "imageUrl": "item/經驗糖果Ｍ.png" },
    { "difficulty": "EXTREME", "category": "EXP", "item": "經驗糖果XL", "effect": "讓角色成長的神奇糖果，全體角色EXP+1", "imageUrl": "item/經驗糖果XL.png" },
    { "difficulty": "EXTREME", "category": "EXP", "item": "神奇糖果", "effect": "讓角色成長的神奇糖果，隨機1名角色EXP+3", "imageUrl": "item/神奇糖果.png" },

    // --- LIVES (Health Recovery) ---
    { "difficulty": "EASY", "category": "LIVES", "item": "愛心糖飾", "effect": "愛心形狀的糖果，玩家生命+1", "imageUrl": "item/愛心糖飾.png" },
    { "difficulty": "NORMAL", "category": "LIVES", "item": "愛心糖飾", "effect": "愛心形狀的糖果，玩家生命+1", "imageUrl": "item/愛心糖飾.png" },
    { "difficulty": "HARD", "category": "LIVES", "item": "愛心糖飾", "effect": "愛心形狀的糖果，玩家生命+2", "imageUrl": "item/愛心糖飾.png" },
    { "difficulty": "EXTREME", "category": "LIVES", "item": "愛心糖飾", "effect": "愛心形狀的糖果，玩家生命+2", "imageUrl": "item/愛心糖飾.png" },

    // --- EVOLUTIONARY ITEMS (PERM_NONE Variants) ---
    { "difficulty": "EASY", "category": "PERM_NONE", "item": "幸運蛋", "effect": "滿載著幸福的蛋，未進化過角色+1攻擊或生命", "imageUrl": "item/幸運蛋.png" },
    { "difficulty": "NORMAL", "category": "PERM_NONE", "item": "幸運蛋", "effect": "滿載著幸福的蛋，未進化過角色+2攻擊或生命", "imageUrl": "item/幸運蛋.png" },
    { "difficulty": "HARD", "category": "PERM_NONE", "item": "幸運蛋", "effect": "滿載著幸福的蛋，未進化過角色+3攻擊或生命", "imageUrl": "item/幸運蛋.png" },
    { "difficulty": "EXTREME", "category": "PERM_NONE", "item": "幸運蛋", "effect": "滿載著幸福的蛋，未進化過角色+4攻擊或生命", "imageUrl": "item/幸運蛋.png" },

    { "difficulty": "NORMAL", "category": "PERM_NONE", "item": "不變之石", "effect": "不會進化的神奇石頭，無法進化的角色+1攻擊或生命", "imageUrl": "item/不變之石.png" },
    { "difficulty": "HARD", "category": "PERM_NONE", "item": "不變之石", "effect": "不會進化的神奇石頭，無法進化的角色+2攻擊或生命", "imageUrl": "item/不變之石.png" },
    { "difficulty": "EXTREME", "category": "PERM_NONE", "item": "不變之石", "effect": "不會進化的神奇石頭，無法進化的角色+3攻擊或生命", "imageUrl": "item/不變之石.png" },

    { "difficulty": "NORMAL", "category": "PERM_NONE", "item": "進化奇石", "effect": "進化的神奇石塊，已進化過的角色+1攻擊或生命", "imageUrl": "item/進化奇石.png" },
    { "difficulty": "HARD", "category": "PERM_NONE", "item": "進化奇石", "effect": "進化的神奇石塊，已進化過的角色+2攻擊或生命", "imageUrl": "item/進化奇石.png" },
    { "difficulty": "EXTREME", "category": "PERM_NONE", "item": "進化奇石", "effect": "進化的神奇石塊，已進化過的角色+3攻擊或生命", "imageUrl": "item/進化奇石.png" }
];
