
export type RewardDifficulty = 'EASY' | 'NORMAL' | 'HARD' | 'EXTREME';

export type RewardCategory =
    | 'GOLD'                // 金幣
    | 'EXP'                 // 經驗
    | 'PERM_NONE'           // 永久能力無羈絆
    | 'PERM_SYNERGY'        // 永久能力有羈絆
    | 'BATTLE_SYNERGY'      // 單次戰鬥能力有羈絆
    | 'BATTLE_NONE';        // 單次戰鬥能力無羈絆

export interface RewardDefinition {
    difficulty: RewardDifficulty;
    category: RewardCategory;
    item: string;
    effect: string;
    imageUrl: string;
    synergyId?: string; // Internal ID if category relates to synergy
}

export const REWARD_DATA: RewardDefinition[] = [
    // --- GOLD ---
    { "difficulty": "EASY", "category": "GOLD", "item": "星星碎片", "effect": "下次準備階段獲得+1金幣", "imageUrl": "item/星星碎片.png" },
    { "difficulty": "NORMAL", "category": "GOLD", "item": "彗星碎片", "effect": "下次準備階段獲得+2金幣", "imageUrl": "item/彗星碎片.png" },
    { "difficulty": "HARD", "category": "GOLD", "item": "金珠", "effect": "下次準備階段獲得+3金幣", "imageUrl": "item/金珠.png" },
    { "difficulty": "EXTREME", "category": "GOLD", "item": "巨大金珠", "effect": "下次準備階段獲得+5金幣", "imageUrl": "item/巨大金珠.png" },

    // --- BATTLE_NONE (Random/Positional/All) ---
    { "difficulty": "EASY", "category": "BATTLE_NONE", "item": "ＰＰ單項小補劑", "effect": "下場我方隨機角色+2攻擊", "imageUrl": "item/ＰＰ單項小補劑.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_NONE", "item": "ＰＰ單項全補劑", "effect": "下場我方隨機角色+4攻擊", "imageUrl": "item/ＰＰ單項全補劑.png" },
    { "difficulty": "HARD", "category": "BATTLE_NONE", "item": "ＰＰ多項小補劑", "effect": "下場我方隨機角色+6攻擊", "imageUrl": "item/ＰＰ多項小補劑.png" },
    { "difficulty": "EXTREME", "category": "BATTLE_NONE", "item": "ＰＰ多項全補劑", "effect": "下場我方隨機角色+10攻擊", "imageUrl": "item/ＰＰ多項全補劑.png" },

    { "difficulty": "EASY", "category": "BATTLE_NONE", "item": "傷藥", "effect": "下場我方隨機角色+2生命", "imageUrl": "item/傷藥.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_NONE", "item": "好傷藥", "effect": "下場我方隨機角色+4生命", "imageUrl": "item/好傷藥.png" },
    { "difficulty": "HARD", "category": "BATTLE_NONE", "item": "厲害傷藥", "effect": "下場我方隨機角色+6生命", "imageUrl": "item/厲害傷藥.png" },
    { "difficulty": "EXTREME", "category": "BATTLE_NONE", "item": "全滿藥", "effect": "下場我方隨機角色+10生命", "imageUrl": "item/全滿藥.png" },

    { "difficulty": "NORMAL", "category": "BATTLE_NONE", "item": "活力碎片", "effect": "下場我方隨機角色+2攻擊與生命", "imageUrl": "item/活力碎片.png" },
    { "difficulty": "HARD", "category": "BATTLE_NONE", "item": "活力塊", "effect": "下場我方隨機角色+3攻擊與生命", "imageUrl": "item/活力塊.png" },

    { "difficulty": "EASY", "category": "BATTLE_NONE", "item": "先制之爪", "effect": "下場我方首位角色+1攻擊", "imageUrl": "item/先制之爪.png" },
    { "difficulty": "EASY", "category": "BATTLE_NONE", "item": "突擊背心", "effect": "下場我方首位角色+1生命", "imageUrl": "item/突擊背心.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_NONE", "item": "先制之爪", "effect": "下場我方首位角色+3攻擊", "imageUrl": "item/先制之爪.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_NONE", "item": "突擊背心", "effect": "下場我方首位角色+3生命", "imageUrl": "item/突擊背心.png" },
    { "difficulty": "HARD", "category": "BATTLE_NONE", "item": "先制之爪", "effect": "下場我方首位角色+5攻擊", "imageUrl": "item/先制之爪.png" },
    { "difficulty": "HARD", "category": "BATTLE_NONE", "item": "突擊背心", "effect": "下場我方首位角色+5生命", "imageUrl": "item/突擊背心.png" },
    { "difficulty": "EXTREME", "category": "BATTLE_NONE", "item": "先制之爪", "effect": "下場我方首位角色+8攻擊", "imageUrl": "item/先制之爪.png" },
    { "difficulty": "EXTREME", "category": "BATTLE_NONE", "item": "突擊背心", "effect": "下場我方首位角色+8生命", "imageUrl": "item/突擊背心.png" },

    { "difficulty": "NORMAL", "category": "BATTLE_NONE", "item": "要害攻擊", "effect": "下場我方全體角色+1攻擊", "imageUrl": "item/要害攻擊.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_NONE", "item": "命中強化", "effect": "下場我方全體角色+1攻擊", "imageUrl": "item/命中強化.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_NONE", "item": "攻擊強化", "effect": "下場我方全體角色+1攻擊", "imageUrl": "item/攻擊強化.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_NONE", "item": "特攻強化", "effect": "下場我方全體角色+1攻擊", "imageUrl": "item/特攻強化.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_NONE", "item": "速度強化", "effect": "下場我方全體角色+1攻擊", "imageUrl": "item/速度強化.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_NONE", "item": "能力防守", "effect": "下場我方全體角色+1生命", "imageUrl": "item/能力防守.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_NONE", "item": "防禦強化", "effect": "下場我方全體角色+1生命", "imageUrl": "item/防禦強化.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_NONE", "item": "特防強化", "effect": "下場我方全體角色+1生命", "imageUrl": "item/特防強化.png" },

    { "difficulty": "HARD", "category": "BATTLE_NONE", "item": "命中強化", "effect": "下場我方全體角色+2攻擊", "imageUrl": "item/命中強化.png" },
    { "difficulty": "HARD", "category": "BATTLE_NONE", "item": "攻擊強化", "effect": "下場我方全體角色+2攻擊", "imageUrl": "item/攻擊強化.png" },
    { "difficulty": "HARD", "category": "BATTLE_NONE", "item": "特攻強化", "effect": "下場我方全體角色+2攻擊", "imageUrl": "item/特攻強化.png" },
    { "difficulty": "HARD", "category": "BATTLE_NONE", "item": "速度強化", "effect": "下場我方全體角色+2攻擊", "imageUrl": "item/速度強化.png" },
    { "difficulty": "HARD", "category": "BATTLE_NONE", "item": "能力防守", "effect": "下場我方全體角色+2生命", "imageUrl": "item/能力防守.png" },
    { "difficulty": "HARD", "category": "BATTLE_NONE", "item": "防禦強化", "effect": "下場我方全體角色+2生命", "imageUrl": "item/防禦強化.png" },
    { "difficulty": "HARD", "category": "BATTLE_NONE", "item": "特防強化", "effect": "下場我方全體角色+2生命", "imageUrl": "item/特防強化.png" },

    // --- BATTLE_SYNERGY ---
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Normal", "item": "柿仔果", "effect": "下場我方守住角色+1攻擊", "imageUrl": "item/柿仔果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Ghost", "item": "謎芝果", "effect": "下場我方詛咒角色+1攻擊", "imageUrl": "item/謎芝果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Grass", "item": "霹靂果", "effect": "下場我方吸取角色+1攻擊", "imageUrl": "item/霹靂果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Fire", "item": "蘋野果", "effect": "下場我方燃盡角色+1攻擊", "imageUrl": "item/蘋野果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Water", "item": "橙橙果", "effect": "下場我方潮旋角色+1攻擊", "imageUrl": "item/橙橙果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Hard", "item": "文柚果", "effect": "下場我方堅硬角色+1攻擊", "imageUrl": "item/文柚果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Cave", "item": "勿花果", "effect": "下場我方挖洞角色+1攻擊", "imageUrl": "item/勿花果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Snow", "item": "莓莓果", "effect": "下場我方降雪角色+1攻擊", "imageUrl": "item/莓莓果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "SwordDance", "item": "櫻子果", "effect": "下場我方劍舞角色+1攻擊", "imageUrl": "item/櫻子果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Psychic", "item": "芒芒果", "effect": "下場我方念力角色+1攻擊", "imageUrl": "item/芒芒果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "BugBite", "item": "木子果", "effect": "下場我方蟲咬角色+1攻擊", "imageUrl": "item/木子果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Thief", "item": "異奇果", "effect": "下場我方小偷角色+1攻擊", "imageUrl": "item/異奇果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Starter", "item": "星桃果", "effect": "下場我方御三家角色+1攻擊", "imageUrl": "item/星桃果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Triplets", "item": "羅子果", "effect": "下場我方三胞胎角色+1攻擊", "imageUrl": "item/羅子果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Angry", "item": "龍火果", "effect": "下場我方憤怒角色+1攻擊", "imageUrl": "item/龍火果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Trick", "item": "福祿果", "effect": "下場我方戲法角色+1攻擊", "imageUrl": "item/福祿果.png" },

    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Normal", "item": "柿仔果", "effect": "下場我方守住角色+1生命", "imageUrl": "item/柿仔果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Ghost", "item": "謎芝果", "effect": "下場我方詛咒角色+1生命", "imageUrl": "item/謎芝果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Grass", "item": "霹靂果", "effect": "下場我方吸取角色+1生命", "imageUrl": "item/霹靂果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Fire", "item": "蘋野果", "effect": "下場我方燃盡角色+1生命", "imageUrl": "item/蘋野果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Water", "item": "橙橙果", "effect": "下場我方潮旋角色+1生命", "imageUrl": "item/橙橙果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Hard", "item": "文柚果", "effect": "下場我方堅硬角色+1生命", "imageUrl": "item/文柚果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Cave", "item": "勿花果", "effect": "下場我方挖洞角色+1生命", "imageUrl": "item/勿花果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Snow", "item": "莓莓果", "effect": "下場我方降雪角色+1生命", "imageUrl": "item/莓莓果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "SwordDance", "item": "櫻子果", "effect": "下場我方劍舞角色+1生命", "imageUrl": "item/櫻子果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Psychic", "item": "芒芒果", "effect": "下場我方念力角色+1生命", "imageUrl": "item/芒芒果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "BugBite", "item": "木子果", "effect": "下場我方蟲咬角色+1生命", "imageUrl": "item/木子果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Thief", "item": "異奇果", "effect": "下場我方小偷角色+1生命", "imageUrl": "item/異奇果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Starter", "item": "星桃果", "effect": "下場我方御三家角色+1生命", "imageUrl": "item/星桃果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Triplets", "item": "羅子果", "effect": "下場我方三胞胎角色+1生命", "imageUrl": "item/羅子果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Angry", "item": "龍火果", "effect": "下場我方憤怒角色+1生命", "imageUrl": "item/龍火果.png" },
    { "difficulty": "EASY", "category": "BATTLE_SYNERGY", "synergyId": "Trick", "item": "福祿果", "effect": "下場我方戲法角色+1生命", "imageUrl": "item/福祿果.png" },

    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Normal", "item": "柿仔果", "effect": "下場我方守住角色+2攻擊", "imageUrl": "item/柿仔果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Ghost", "item": "謎芝果", "effect": "下場我方詛咒角色+2攻擊", "imageUrl": "item/謎芝果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Grass", "item": "霹靂果", "effect": "下場我方吸取角色+2攻擊", "imageUrl": "item/霹靂果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Fire", "item": "蘋野果", "effect": "下場我方燃盡角色+2攻擊", "imageUrl": "item/蘋野果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Water", "item": "橙橙果", "effect": "下場我方潮旋角色+2攻擊", "imageUrl": "item/橙橙果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Hard", "item": "文柚果", "effect": "下場我方堅硬角色+2攻擊", "imageUrl": "item/文柚果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Cave", "item": "勿花果", "effect": "下場我方挖洞角色+2攻擊", "imageUrl": "item/勿花果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Snow", "item": "莓莓果", "effect": "下場我方降雪角色+2攻擊", "imageUrl": "item/莓莓果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "SwordDance", "item": "櫻子果", "effect": "下場我方劍舞角色+2攻擊", "imageUrl": "item/櫻子果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Psychic", "item": "芒芒果", "effect": "下場我方念力角色+2攻擊", "imageUrl": "item/芒芒果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "BugBite", "item": "木子果", "effect": "下場我方蟲咬角色+2攻擊", "imageUrl": "item/木子果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Thief", "item": "異奇果", "effect": "下場我方小偷角色+2攻擊", "imageUrl": "item/異奇果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Starter", "item": "星桃果", "effect": "下場我方御三家角色+2攻擊", "imageUrl": "item/星桃果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Triplets", "item": "羅子果", "effect": "下場我方三胞胎角色+2攻擊", "imageUrl": "item/羅子果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Angry", "item": "龍火果", "effect": "下場我方憤怒角色+2攻擊", "imageUrl": "item/龍火果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Trick", "item": "福祿果", "effect": "下場我方戲法角色+2攻擊", "imageUrl": "item/福祿果.png" },

    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Normal", "item": "柿仔果", "effect": "下場我方守住角色+2生命", "imageUrl": "item/柿仔果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Ghost", "item": "謎芝果", "effect": "下場我方詛咒角色+2生命", "imageUrl": "item/謎芝果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Grass", "item": "霹靂果", "effect": "下場我方吸取角色+2生命", "imageUrl": "item/霹靂果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Fire", "item": "蘋野果", "effect": "下場我方燃盡角色+2生命", "imageUrl": "item/蘋野果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Water", "item": "橙橙果", "effect": "下場我方潮旋角色+2生命", "imageUrl": "item/橙橙果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Hard", "item": "文柚果", "effect": "下場我方堅硬角色+2生命", "imageUrl": "item/文柚果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Cave", "item": "勿花果", "effect": "下場我方挖洞角色+2生命", "imageUrl": "item/勿花果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Snow", "item": "莓莓果", "effect": "下場我方降雪角色+2生命", "imageUrl": "item/莓莓果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "SwordDance", "item": "櫻子果", "effect": "下場我方劍舞角色+2生命", "imageUrl": "item/櫻子果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Psychic", "item": "芒芒果", "effect": "下場我方念力角色+2生命", "imageUrl": "item/芒芒果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "BugBite", "item": "木子果", "effect": "下場我方蟲咬角色+2生命", "imageUrl": "item/木子果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Thief", "item": "異奇果", "effect": "下場我方小偷角色+2生命", "imageUrl": "item/異奇果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Starter", "item": "星桃果", "effect": "下場我方御三家角色+2生命", "imageUrl": "item/星桃果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Triplets", "item": "羅子果", "effect": "下場我方三胞胎角色+2生命", "imageUrl": "item/羅子果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Angry", "item": "龍火果", "effect": "下場我方憤怒角色+2生命", "imageUrl": "item/龍火果.png" },
    { "difficulty": "NORMAL", "category": "BATTLE_SYNERGY", "synergyId": "Trick", "item": "福祿果", "effect": "下場我方戲法角色+2生命", "imageUrl": "item/福祿果.png" },

    { "difficulty": "HARD", "category": "BATTLE_SYNERGY", "synergyId": "Normal", "item": "星桃果", "effect": "下場雙方守住角色+3攻擊與生命", "imageUrl": "item/淨空石板.png" },
    { "difficulty": "HARD", "category": "BATTLE_SYNERGY", "synergyId": "Ghost", "item": "羅子果", "effect": "下場雙方詛咒角色+3攻擊與生命", "imageUrl": "item/妖怪石板.png" },
    { "difficulty": "HARD", "category": "BATTLE_SYNERGY", "synergyId": "Grass", "item": "龍火果", "effect": "下場雙方吸取角色+3攻擊與生命", "imageUrl": "item/碧綠石板.png" },
    { "difficulty": "HARD", "category": "BATTLE_SYNERGY", "synergyId": "Fire", "item": "福祿果", "effect": "下場雙方燃盡角色+3攻擊與生命", "imageUrl": "item/火球石板.png" },
    { "difficulty": "HARD", "category": "BATTLE_SYNERGY", "synergyId": "Water", "item": "水滴石板", "effect": "下場雙方潮旋角色+3攻擊與生命", "imageUrl": "item/水滴石板.png" },
    { "difficulty": "HARD", "category": "BATTLE_SYNERGY", "synergyId": "Hard", "item": "鋼鐵石板", "effect": "下場雙方堅硬角色+3攻擊與生命", "imageUrl": "item/鋼鐵石板.png" },
    { "difficulty": "HARD", "category": "BATTLE_SYNERGY", "synergyId": "Cave", "item": "大地石板", "effect": "下場雙方挖洞角色+3攻擊與生命", "imageUrl": "item/大地石板.png" },
    { "difficulty": "HARD", "category": "BATTLE_SYNERGY", "synergyId": "Snow", "item": "冰柱石板", "effect": "下場雙方降雪角色+3攻擊與生命", "imageUrl": "item/冰柱石板.png" },
    { "difficulty": "HARD", "category": "BATTLE_SYNERGY", "synergyId": "SwordDance", "item": "拳頭石板", "effect": "下場雙方劍舞角色+3攻擊與生命", "imageUrl": "item/拳頭石板.png" },
    { "difficulty": "HARD", "category": "BATTLE_SYNERGY", "synergyId": "Psychic", "item": "普通石板", "effect": "下場雙方念力角色+3攻擊與生命", "imageUrl": "item/普通石板.png" },
    { "difficulty": "HARD", "category": "BATTLE_SYNERGY", "synergyId": "BugBite", "item": "玉蟲石板", "effect": "下場雙方蟲咬角色+3攻擊與生命", "imageUrl": "item/玉蟲石板.png" },
    { "difficulty": "HARD", "category": "BATTLE_SYNERGY", "synergyId": "Thief", "item": "惡顏石板", "effect": "下場雙方小偷角色+3攻擊與生命", "imageUrl": "item/惡顏石板.png" },

    { "difficulty": "EXTREME", "category": "BATTLE_SYNERGY", "synergyId": "Normal", "item": "淨空石板", "effect": "下場雙方守住角色+5攻擊與生命", "imageUrl": "item/淨空石板.png" },
    { "difficulty": "EXTREME", "category": "BATTLE_SYNERGY", "synergyId": "Ghost", "item": "妖怪石板", "effect": "下場雙方詛咒角色+5攻擊與生命", "imageUrl": "item/妖怪石板.png" },
    { "difficulty": "EXTREME", "category": "BATTLE_SYNERGY", "synergyId": "Grass", "item": "碧綠石板", "effect": "下場雙方吸取角色+5攻擊與生命", "imageUrl": "item/碧綠石板.png" },
    { "difficulty": "EXTREME", "category": "BATTLE_SYNERGY", "synergyId": "Fire", "item": "火球石板", "effect": "下場雙方燃盡角色+5攻擊與生命", "imageUrl": "item/火球石板.png" },
    { "difficulty": "EXTREME", "category": "BATTLE_SYNERGY", "synergyId": "Water", "item": "水滴石板", "effect": "下場雙方潮旋角色+5攻擊與生命", "imageUrl": "item/水滴石板.png" },
    { "difficulty": "EXTREME", "category": "BATTLE_SYNERGY", "synergyId": "Hard", "item": "鋼鐵石板", "effect": "下場雙方堅硬角色+5攻擊與生命", "imageUrl": "item/鋼鐵石板.png" },
    { "difficulty": "EXTREME", "category": "BATTLE_SYNERGY", "synergyId": "Cave", "item": "大地石板", "effect": "下場雙方挖洞角色+5攻擊與生命", "imageUrl": "item/大地石板.png" },
    { "difficulty": "EXTREME", "category": "BATTLE_SYNERGY", "synergyId": "Snow", "item": "冰柱石板", "effect": "下場雙方降雪角色+5攻擊與生命", "imageUrl": "item/冰柱石板.png" },
    { "difficulty": "EXTREME", "category": "BATTLE_SYNERGY", "synergyId": "SwordDance", "item": "拳頭石板", "effect": "下場雙方劍舞角色+5攻擊與生命", "imageUrl": "item/拳頭石板.png" },
    { "difficulty": "EXTREME", "category": "BATTLE_SYNERGY", "synergyId": "Psychic", "item": "普通石板", "effect": "下場雙方念力角色+5攻擊與生命", "imageUrl": "item/普通石板.png" },
    { "difficulty": "EXTREME", "category": "BATTLE_SYNERGY", "synergyId": "BugBite", "item": "玉蟲石板", "effect": "下場雙方蟲咬角色+5攻擊與生命", "imageUrl": "item/玉蟲石板.png" },
    { "difficulty": "EXTREME", "category": "BATTLE_SYNERGY", "synergyId": "Thief", "item": "惡顏石板", "effect": "下場雙方小偷角色+5攻擊與生命", "imageUrl": "item/惡顏石板.png" },

    // --- PERM_NONE ---
    { "difficulty": "HARD", "category": "PERM_NONE", "item": "腐朽的劍", "effect": "隊伍中的首位角色+3攻擊", "imageUrl": "item/腐朽的劍.png" },
    { "difficulty": "HARD", "category": "PERM_NONE", "item": "腐朽的盾", "effect": "隊伍中的首位角色+3生命", "imageUrl": "item/腐朽的盾.png" },
    { "difficulty": "EXTREME", "category": "PERM_NONE", "item": "腐朽的劍", "effect": "隊伍中的首位角色+5攻擊", "imageUrl": "item/腐朽的劍.png" },
    { "difficulty": "EXTREME", "category": "PERM_NONE", "item": "腐朽的盾", "effect": "隊伍中的首位角色+5生命", "imageUrl": "item/腐朽的盾.png" },

    { "difficulty": "HARD", "category": "PERM_NONE", "item": "力量鏡", "effect": "隊伍中的全體角色+2攻擊-1生命", "imageUrl": "item/力量鏡.png" },
    { "difficulty": "HARD", "category": "PERM_NONE", "item": "力量護踝", "effect": "隊伍中的全體角色+2攻擊-1生命", "imageUrl": "item/力量護踝.png" },
    { "difficulty": "HARD", "category": "PERM_NONE", "item": "力量護腕", "effect": "隊伍中的全體角色+2攻擊-1生命", "imageUrl": "item/力量護腕.png" },
    { "difficulty": "HARD", "category": "PERM_NONE", "item": "力量負重", "effect": "隊伍中的全體角色+2生命-1攻擊", "imageUrl": "item/力量負重.png" },
    { "difficulty": "HARD", "category": "PERM_NONE", "item": "力量腰帶", "effect": "隊伍中的全體角色+2生命-1攻擊", "imageUrl": "item/力量腰帶.png" },
    { "difficulty": "HARD", "category": "PERM_NONE", "item": "力量束帶", "effect": "隊伍中的全體角色+2生命-1攻擊", "imageUrl": "item/力量束帶.png" },
    { "difficulty": "EXTREME", "category": "PERM_NONE", "item": "力量鏡", "effect": "隊伍中的全體角色+4攻擊-2生命", "imageUrl": "item/力量鏡.png" },
    { "difficulty": "EXTREME", "category": "PERM_NONE", "item": "力量護踝", "effect": "隊伍中的全體角色+4攻擊-2生命", "imageUrl": "item/力量護踝.png" },
    { "difficulty": "EXTREME", "category": "PERM_NONE", "item": "力量護腕", "effect": "隊伍中的全體角色+4攻擊-2生命", "imageUrl": "item/力量護腕.png" },
    { "difficulty": "EXTREME", "category": "PERM_NONE", "item": "力量負重", "effect": "隊伍中的全體角色+4生命-2攻擊", "imageUrl": "item/力量負重.png" },
    { "difficulty": "EXTREME", "category": "PERM_NONE", "item": "力量腰帶", "effect": "隊伍中的全體角色+4生命-2攻擊", "imageUrl": "item/力量腰帶.png" },
    { "difficulty": "EXTREME", "category": "PERM_NONE", "item": "力量束帶", "effect": "隊伍中的全體角色+4生命-2攻擊", "imageUrl": "item/力量束帶.png" },

    // --- PERM_SYNERGY ---
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Normal", "item": "絲綢圍巾", "effect": "隊伍中的守住角色+1攻擊", "imageUrl": "item/絲綢圍巾.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Ghost", "item": "詛咒之符", "effect": "隊伍中的詛咒角色+1攻擊", "imageUrl": "item/詛咒之符.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Grass", "item": "奇跡種子", "effect": "隊伍中的吸取角色+1攻擊", "imageUrl": "item/奇跡種子.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Fire", "item": "木炭", "effect": "隊伍中的燃盡角色+1攻擊", "imageUrl": "item/木炭.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Water", "item": "神秘水滴", "effect": "隊伍中的潮旋角色+1攻擊", "imageUrl": "item/神秘水滴.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Hard", "item": "硬石頭", "effect": "隊伍中的堅硬角色+1攻擊", "imageUrl": "item/硬石頭.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Cave", "item": "柔軟沙子", "effect": "隊伍中的挖洞角色+1攻擊", "imageUrl": "item/柔軟沙子.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Snow", "item": "不融冰", "effect": "隊伍中的降雪角色+1攻擊", "imageUrl": "item/不融冰.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "SwordDance", "item": "黑帶", "effect": "隊伍中的劍舞角色+1攻擊", "imageUrl": "item/黑帶.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Psychic", "item": "彎曲的湯匙", "effect": "隊伍中的念力角色+1攻擊", "imageUrl": "item/彎曲的湯匙.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "BugBite", "item": "銀粉", "effect": "隊伍中的蟲咬角色+1攻擊", "imageUrl": "item/銀粉.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Thief", "item": "黑色眼鏡", "effect": "隊伍中的小偷角色+1攻擊", "imageUrl": "item/黑色眼鏡.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Starter", "item": "幸運草糖飾", "effect": "隊伍中的御三家角色+1攻擊", "imageUrl": "item/幸運草糖飾.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Triplets", "item": "野莓糖飾", "effect": "隊伍中的三胞胎角色+1攻擊", "imageUrl": "item/野莓糖飾.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Angry", "item": "拳擊手套", "effect": "隊伍中的憤怒角色+1攻擊", "imageUrl": "item/拳擊手套.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Trick", "item": "客房服務", "effect": "隊伍中的戲法角色+1攻擊", "imageUrl": "item/客房服務.png" },

    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Normal", "item": "絲綢圍巾", "effect": "隊伍中的守住角色+1生命", "imageUrl": "item/絲綢圍巾.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Ghost", "item": "詛咒之符", "effect": "隊伍中的詛咒角色+1生命", "imageUrl": "item/詛咒之符.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Grass", "item": "奇跡種子", "effect": "隊伍中的吸取角色+1生命", "imageUrl": "item/奇跡種子.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Fire", "item": "木炭", "effect": "隊伍中的燃盡角色+1生命", "imageUrl": "item/木炭.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Water", "item": "神秘水滴", "effect": "隊伍中的潮旋角色+1生命", "imageUrl": "item/神秘水滴.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Hard", "item": "硬石頭", "effect": "隊伍中的堅硬角色+1生命", "imageUrl": "item/硬石頭.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Cave", "item": "柔軟沙子", "effect": "隊伍中的挖洞角色+1生命", "imageUrl": "item/柔軟沙子.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Snow", "item": "不融冰", "effect": "隊伍中的降雪角色+1生命", "imageUrl": "item/不融冰.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "SwordDance", "item": "黑帶", "effect": "隊伍中的劍舞角色+1生命", "imageUrl": "item/黑帶.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Psychic", "item": "彎曲的湯匙", "effect": "隊伍中的念力角色+1生命", "imageUrl": "item/彎曲的湯匙.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "BugBite", "item": "銀粉", "effect": "隊伍中的蟲咬角色+1生命", "imageUrl": "item/銀粉.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Thief", "item": "黑色眼鏡", "effect": "隊伍中的小偷角色+1生命", "imageUrl": "item/黑色眼鏡.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Starter", "item": "幸運草糖飾", "effect": "隊伍中的御三家角色+1生命", "imageUrl": "item/幸運草糖飾.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Triplets", "item": "野莓糖飾", "effect": "隊伍中的三胞胎角色+1生命", "imageUrl": "item/野莓糖飾.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Angry", "item": "拳擊手套", "effect": "隊伍中的憤怒角色+1生命", "imageUrl": "item/拳擊手套.png" },
    { "difficulty": "NORMAL", "category": "PERM_SYNERGY", "synergyId": "Trick", "item": "客房服務", "effect": "隊伍中的戲法角色+1生命", "imageUrl": "item/客房服務.png" },

    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Normal", "item": "絲綢圍巾", "effect": "隊伍中的守住角色+2攻擊", "imageUrl": "item/絲綢圍巾.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Ghost", "item": "詛咒之符", "effect": "隊伍中的詛咒角色+2攻擊", "imageUrl": "item/詛咒之符.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Grass", "item": "奇跡種子", "effect": "隊伍中的吸取角色+2攻擊", "imageUrl": "item/奇跡種子.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Fire", "item": "木炭", "effect": "隊伍中的燃盡角色+2攻擊", "imageUrl": "item/木炭.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Water", "item": "神秘水滴", "effect": "隊伍中的潮旋角色+2攻擊", "imageUrl": "item/神秘水滴.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Hard", "item": "硬石頭", "effect": "隊伍中的堅硬角色+2攻擊", "imageUrl": "item/硬石頭.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Cave", "item": "柔軟沙子", "effect": "隊伍中的挖洞角色+2攻擊", "imageUrl": "item/柔軟沙子.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Snow", "item": "不融冰", "effect": "隊伍中的降雪角色+2攻擊", "imageUrl": "item/不融冰.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "SwordDance", "item": "黑帶", "effect": "隊伍中的劍舞角色+2攻擊", "imageUrl": "item/黑帶.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Psychic", "item": "彎曲的湯匙", "effect": "隊伍中的念力角色+2攻擊", "imageUrl": "item/彎曲的湯匙.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "BugBite", "item": "銀粉", "effect": "隊伍中的蟲咬角色+2攻擊", "imageUrl": "item/銀粉.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Thief", "item": "黑色眼鏡", "effect": "隊伍中的小偷角色+2攻擊", "imageUrl": "item/黑色眼鏡.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Starter", "item": "幸運草糖飾", "effect": "隊伍中的御三家角色+2攻擊", "imageUrl": "item/幸運草糖飾.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Triplets", "item": "野莓糖飾", "effect": "隊伍中的三胞胎角色+2攻擊", "imageUrl": "item/野莓糖飾.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Angry", "item": "拳擊手套", "effect": "隊伍中的憤怒角色+2攻擊", "imageUrl": "item/拳擊手套.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Trick", "item": "客房服務", "effect": "隊伍中的戲法角色+2攻擊", "imageUrl": "item/客房服務.png" },

    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Normal", "item": "絲綢圍巾", "effect": "隊伍中的守住角色+2生命", "imageUrl": "item/絲綢圍巾.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Ghost", "item": "詛咒之符", "effect": "隊伍中的詛咒角色+2生命", "imageUrl": "item/詛咒之符.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Grass", "item": "奇跡種子", "effect": "隊伍中的吸取角色+2生命", "imageUrl": "item/奇跡種子.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Fire", "item": "木炭", "effect": "隊伍中的燃盡角色+2生命", "imageUrl": "item/木炭.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Water", "item": "神秘水滴", "effect": "隊伍中的潮旋角色+2生命", "imageUrl": "item/神秘水滴.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Hard", "item": "硬石頭", "effect": "隊伍中的堅硬角色+2生命", "imageUrl": "item/硬石頭.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Cave", "item": "柔軟沙子", "effect": "隊伍中的挖洞角色+2生命", "imageUrl": "item/柔軟沙子.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Snow", "item": "不融冰", "effect": "隊伍中的降雪角色+2生命", "imageUrl": "item/不融冰.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "SwordDance", "item": "黑帶", "effect": "隊伍中的劍舞角色+2生命", "imageUrl": "item/黑帶.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Psychic", "item": "彎曲的湯匙", "effect": "隊伍中的念力角色+2生命", "imageUrl": "item/彎曲的湯匙.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "BugBite", "item": "銀粉", "effect": "隊伍中的蟲咬角色+2生命", "imageUrl": "item/銀粉.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Thief", "item": "黑色眼鏡", "effect": "隊伍中的小偷角色+2生命", "imageUrl": "item/黑色眼鏡.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Starter", "item": "幸運草糖飾", "effect": "隊伍中的御三家角色+2生命", "imageUrl": "item/幸運草糖飾.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Triplets", "item": "野莓糖飾", "effect": "隊伍中的三胞胎角色+2生命", "imageUrl": "item/野莓糖飾.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Angry", "item": "拳擊手套", "effect": "隊伍中的憤怒角色+2生命", "imageUrl": "item/拳擊手套.png" },
    { "difficulty": "HARD", "category": "PERM_SYNERGY", "synergyId": "Trick", "item": "客房服務", "effect": "隊伍中的戲法角色+2生命", "imageUrl": "item/客房服務.png" },

    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Normal", "item": "絲綢圍巾", "effect": "隊伍中的守住角色+3攻擊", "imageUrl": "item/絲綢圍巾.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Ghost", "item": "詛咒之符", "effect": "隊伍中的詛咒角色+3攻擊", "imageUrl": "item/詛咒之符.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Grass", "item": "奇跡種子", "effect": "隊伍中的吸取角色+3攻擊", "imageUrl": "item/奇跡種子.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Fire", "item": "木炭", "effect": "隊伍中的燃盡角色+3攻擊", "imageUrl": "item/木炭.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Water", "item": "神秘水滴", "effect": "隊伍中的潮旋角色+3攻擊", "imageUrl": "item/神秘水滴.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Hard", "item": "硬石頭", "effect": "隊伍中的堅硬角色+3攻擊", "imageUrl": "item/硬石頭.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Cave", "item": "柔軟沙子", "effect": "隊伍中的挖洞角色+3攻擊", "imageUrl": "item/柔軟沙子.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Snow", "item": "不融冰", "effect": "隊伍中的降雪角色+3攻擊", "imageUrl": "item/不融冰.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "SwordDance", "item": "黑帶", "effect": "隊伍中的劍舞角色+3攻擊", "imageUrl": "item/黑帶.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Psychic", "item": "彎曲的湯匙", "effect": "隊伍中的念力角色+3攻擊", "imageUrl": "item/彎曲的湯匙.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "BugBite", "item": "銀粉", "effect": "隊伍中的蟲咬角色+3攻擊", "imageUrl": "item/銀粉.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Thief", "item": "黑色眼鏡", "effect": "隊伍中的小偷角色+3攻擊", "imageUrl": "item/黑色眼鏡.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Starter", "item": "幸運草糖飾", "effect": "隊伍中的御三家角色+3攻擊", "imageUrl": "item/幸運草糖飾.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Triplets", "item": "野莓糖飾", "effect": "隊伍中的三胞胎角色+3攻擊", "imageUrl": "item/野莓糖飾.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Angry", "item": "拳擊手套", "effect": "隊伍中的憤怒角色+3攻擊", "imageUrl": "item/拳擊手套.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Trick", "item": "客房服務", "effect": "隊伍中的戲法角色+3攻擊", "imageUrl": "item/客房服務.png" },

    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Normal", "item": "絲綢圍巾", "effect": "隊伍中的守住角色+3生命", "imageUrl": "item/絲綢圍巾.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Ghost", "item": "詛咒之符", "effect": "隊伍中的詛咒角色+3生命", "imageUrl": "item/詛咒之符.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Grass", "item": "奇跡種子", "effect": "隊伍中的吸取角色+3生命", "imageUrl": "item/奇跡種子.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Fire", "item": "木炭", "effect": "隊伍中的燃盡角色+3生命", "imageUrl": "item/木炭.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Water", "item": "神秘水滴", "effect": "隊伍中的潮旋角色+3生命", "imageUrl": "item/神秘水滴.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Hard", "item": "硬石頭", "effect": "隊伍中的堅硬角色+3生命", "imageUrl": "item/硬石頭.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Cave", "item": "柔軟沙子", "effect": "隊伍中的挖洞角色+3生命", "imageUrl": "item/柔軟沙子.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Snow", "item": "不融冰", "effect": "隊伍中的降雪角色+3生命", "imageUrl": "item/不融冰.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "SwordDance", "item": "黑帶", "effect": "隊伍中的劍舞角色+3生命", "imageUrl": "item/黑帶.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Psychic", "item": "彎曲的湯匙", "effect": "隊伍中的念力角色+3生命", "imageUrl": "item/彎曲的湯匙.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "BugBite", "item": "銀粉", "effect": "隊伍中的蟲咬角色+3生命", "imageUrl": "item/銀粉.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Thief", "item": "黑色眼鏡", "effect": "隊伍中的小偷角色+3生命", "imageUrl": "item/黑色眼鏡.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Starter", "item": "幸運草糖飾", "effect": "隊伍中的御三家角色+3生命", "imageUrl": "item/幸運草糖飾.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Triplets", "item": "野莓糖飾", "effect": "隊伍中的三胞胎角色+3生命", "imageUrl": "item/野莓糖飾.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Angry", "item": "拳擊手套", "effect": "隊伍中的憤怒角色+3生命", "imageUrl": "item/拳擊手套.png" },
    { "difficulty": "EXTREME", "category": "PERM_SYNERGY", "synergyId": "Trick", "item": "客房服務", "effect": "隊伍中的戲法角色+3生命", "imageUrl": "item/客房服務.png" },

    // --- EXP ---
    { "difficulty": "EASY", "category": "EXP", "item": "經驗糖果XS", "effect": "隊伍中的隨機角色EXP+1", "imageUrl": "item/經驗糖果ＸＳ.png" },
    { "difficulty": "NORMAL", "category": "EXP", "item": "經驗糖果S", "effect": "隊伍中的隨機兩位角色EXP+1", "imageUrl": "item/經驗糖果Ｓ.png" },
    { "difficulty": "HARD", "category": "EXP", "item": "經驗糖果M", "effect": "隊伍中的隨機三位角色EXP+1", "imageUrl": "item/經驗糖果Ｍ.png" },
    { "difficulty": "EXTREME", "category": "EXP", "item": "經驗糖果XL", "effect": "隊伍中的全體角色EXP+1", "imageUrl": "item/經驗糖果ＸＬ.png" },
    { "difficulty": "EXTREME", "category": "EXP", "item": "神奇糖果", "effect": "隊伍中的隨機角色EXP+3", "imageUrl": "item/神奇糖果.png" }
];
